apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: daprResiliency

spec:
  policies:
    retries:
      retryForever:
        policy: constant
        duration: 1s
        maxRetries: -1

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s
        trip: consecutiveFailures >= 5

  targets:
    apps:
      badgerer-image-generator:
        retry: retryForever
        circuitBreaker: simpleCB